# Arg 1: a dot file representing a CFG, generated by opt -dot-cfg
OUTPUT=${1%.*}.labels-only.dot
# remove everything in the label except the first line.
sed 's/(label="\{[^:]*:)[^}]*\}/\1}/g' $1 > $OUTPUT
